# Generated by Django 5.0.6 on 2024-05-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_alter_reserva_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='horario_final',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horario_inicio',
            field=models.TextField(),
        ),
    ]
