# Generated by Django 5.0.6 on 2024-06-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_alter_reserva_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='horario_final',
            field=models.TextField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horario_inicio',
            field=models.TextField(default='12:00'),
        ),
    ]
