# Generated by Django 5.0.6 on 2024-06-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_alter_reserva_horario_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='horario_final',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horario_inicio',
            field=models.TextField(null=True),
        ),
    ]
