# Generated by Django 5.0.6 on 2024-06-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0007_alter_reserva_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='id_cliente',
            field=models.IntegerField(),
        ),
    ]
