# Generated by Django 5.0.6 on 2024-06-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0010_alter_reserva_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
