# Generated by Django 5.0.6 on 2024-06-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0012_remove_reserva_mesa_alter_reserva_id_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='mesa',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
