# Generated by Django 5.0.6 on 2024-06-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0013_reserva_mesa_alter_reserva_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='horario_final',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horario_inicio',
            field=models.TimeField(null=True),
        ),
    ]
