# Generated by Django 5.0.6 on 2024-06-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0014_alter_reserva_horario_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='mesa',
            field=models.IntegerField(default=0),
        ),
    ]
