# Generated by Django 5.0.6 on 2024-06-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0015_alter_reserva_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='id_cliente',
            field=models.IntegerField(),
        ),
    ]
